# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/kcl-rb/all/kcl-rb.rbi
#
# kcl-rb-1.0.1

module Kcl
  def self.config; end
  def self.configure; end
  def self.logger; end
end
