AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "demo/vendor/**/*"

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*

Lint/NonDeterministicRequireOrder:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstMethodArgumentLineBreak:
  Enabled: true
  Exclude:
    - spec/**/*.rb
    - test/**/*.rb

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line
  Exclude:
    - spec/**/*.rb
    - test/**/*.rb

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Incompatible with RSpec idioms
# https://github.com/rubocop/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/AssignmentInCondition:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  AllowKeywordBlockArguments: true

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Exclude:
    - Gemfile
    - "*.gemspec"
    - spec/**/*.rb

Metrics/ClassLength:
  Max: 250
  Exclude:
    - spec/**/*.rb

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 50
  CountAsOne: ['array', 'heredoc', 'hash']

Naming/VariableNumber:
  EnforcedStyle: snake_case
  Exclude:
    - "**/config/routes.rb"

# can I remove?
Style/BlockComments:
  Enabled: false

Style/BlockDelimiters:
  IgnoredMethods:
    - lambda
    - proc

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

# can I remove?
Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  EnforcedStyle: braces

Style/NegatedIf:
  Enabled: false

# can I remove it?
Style/NumericPredicate:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  AllowMethodsWithArguments: true
