name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  linters:
    runs-on: ubuntu-latest

    env:
      RUBYOPT: -EUTF-8

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Setup Reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Run Rubocop
      run: reviewdog -reporter=github-pr-review -tee -runners=Rubocop -fail-on-error=true
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  typecheck:
    runs-on: ubuntu-latest

    env:
      RUBYOPT: -EUTF-8

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run sorbet
      run: bundle exec srb
  testing:
    runs-on: ubuntu-latest

    env:
      RUBYOPT: -EUTF-8

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Setup Reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Up docker-compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.24

    - id: init
      working-directory: ${{ github.workspace }}/terraform
      run: |
        terraform init
        terraform apply -auto-approve -no-color

    - name: RSpec & Undercover
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        source .env
        bundle exec rspec
        git fetch
        reviewdog -reporter=github-pr-review -tee -runners=Undercover
